### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by MostHated** [nukadelic/UnityEditorIcons#1]
Hey there,
    Thanks for making/sharing this. While the tool seems quite useful, I am too paranoid/cautious to use anything unless I know for sure it is licensed to do so. I was hoping that you might be willing to add a license to the repo? 

Thanks! 
-MH

**Comment by nukadelic** [comment]
unlicensed - use it however u want

**Comment by MostHated** [comment]
Good deal. I appreciate you letting me know.
